jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: buildpack-deps:trusty

    working_directory: ~/

    steps:
      # command will execute in trusty container
      # and can access mongo on localhost
      - echo "success"
