jobs:
  build:
    docker:
    # Primary container image where all steps run.
     - image: buildpack-deps:trusty

    working_directory: ~/

    steps:
      - run: |
        apt-get update
        apt-get install -y devscripts debhelper libpq-dev postgresql-server-dev-all libpam0g-dev libssl-dev libmemcached-dev dh-autoreconf ruby libhiredis-dev
        debuild -us -uc -b
